"""Initial migration

Revision ID: 073ef543d077
Revises: 
Create Date: 2025-07-22 19:30:18.898326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '073ef543d077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('newsletter_subscribers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('social_media', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=True),
    sa.Column('is_gluten_free', sa.Boolean(), nullable=True),
    sa.Column('is_spicy', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['menu_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kycs')
    op.drop_table('assets')
    op.drop_table('otps')
    op.drop_table('bankAccounts')
    op.drop_table('migrations')
    op.drop_table('orders')
    op.drop_table('ads')
    op.drop_table('wallets')
    op.drop_table('users')
    op.drop_table('refreshTokens')
    op.drop_table('notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userType', postgresql.ENUM('admin', 'user', name='notifications_usertype_enum'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deviceToken', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_692a909ee0fa9383e7859f9b406'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_6a72c3c0f683f6462415e653c3a'))
    )
    op.create_table('refreshTokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refreshToken', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_265bec4e500714d5269580a0219'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_c4a0078b846c2c4508473680625'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('firstName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middleName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('businessName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('googleId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('emailVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('phoneNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phoneVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deviceToken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notification', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'deactivated', 'pending', 'deleted', name='users_status_enum'), server_default=sa.text("'active'::users_status_enum"), autoincrement=False, nullable=False),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('accountLevel', postgresql.ENUM('level_1', 'level_2', 'level_3', name='users_accountlevel_enum'), server_default=sa.text("'level_1'::users_accountlevel_enum"), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nationality', sa.VARCHAR(), server_default=sa.text("'Nigeria'::character varying"), autoincrement=False, nullable=False),
    sa.Column('dateOfBirth', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"key": null, "url": null}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('twoFactorAuth', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"qrcode": null, "secretKey": null}\'::jsonb'), autoincrement=False, nullable=False),
    sa.Column('twoFactorAuthEnabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('lastLogin', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('userType', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK_a3ffb1c0c8416b9fc6f907b7433'),
    sa.UniqueConstraint('email', name='UQ_97672ac88f789774dd47f7c8be3', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('xNGN', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('SOL', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('BTC', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('USDT', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('USDT_ETH', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('USDT_SOL', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('ETH', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('TRX', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('xNGNLocked', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('SOLLocked', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('BTCLocked', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('USDTLocked', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('ETHLocked', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('NGNMaxDailyWithdrawal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('USDMaxDailyWithdrawallimit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('AdsLimit', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('vaultAccountId', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('activated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('onHold', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('blockWallet', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('pin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pinSet', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('bankAccountId', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bankAccountId'], ['bankAccounts.id'], name=op.f('FK_a4547cfec15f0a6615ee752c5ab'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_2ecdb33f23e9a6fc392025c0b97'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_8402e5df5a30a229380e83e4f7e'))
    )
    op.create_table('ads',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('orderType', postgresql.ENUM('sell', 'buy', name='ads_ordertype_enum'), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('amountAvailable', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('amountFilled', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('minimumLimit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('maximumLimit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('fee', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('expiryDate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'NGN'::character varying"), autoincrement=False, nullable=False),
    sa.Column('priceType', postgresql.ENUM('static', 'dynamic', name='ads_pricetype_enum'), autoincrement=False, nullable=False),
    sa.Column('priceLowerLimit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('priceUpperLimit', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'disabled', 'closed', name='ads_status_enum'), server_default=sa.text("'active'::ads_status_enum"), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-06-30 10:00:29.639592+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2025-06-30 10:00:29.639592+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='FK_e72da72588dc5b91427a9adda71', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='PK_a7af7d1998037a97076f758fc23'),
    postgresql_ignore_search_path=False
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('buyerId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('merchantId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adsId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('adType', postgresql.ENUM('buy', 'sell', name='orders_adtype_enum'), autoincrement=False, nullable=False),
    sa.Column('transactionId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'completed', 'failed', name='orders_status_enum'), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transactionFee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('transactionFeeReference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('transactionFeePaid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('networkFee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('networkFeeInUSD', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['adsId'], ['ads.id'], name=op.f('FK_68f18d965f5be7fc32db23edf32'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['buyerId'], ['users.id'], name=op.f('FK_9877ffd9a491c3e82f5b32d4f4d'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchantId'], ['users.id'], name=op.f('FK_c9e4efcabb250e585daa4c19624'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_710e2d4957aa5878dfe94e4ac2f'))
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_8c82d7f526340ab734260ea46be'))
    )
    op.create_table('bankAccounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('walletId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bankAccountType', postgresql.ENUM('deposit', 'withdrawal', name='bankAccounts_bankaccounttype_enum'), autoincrement=False, nullable=False),
    sa.Column('bankAccountReference', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accountNumber', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accountName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bankName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bankCode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_b2e8e550e9a9cf8cae725d3903e'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_114087aa41aaa1a81f6cbb54475'))
    )
    op.create_table('otps',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('email_verification', 'forgot_password', 'phone_verification', name='otps_type_enum'), autoincrement=False, nullable=False),
    sa.Column('expiresAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_82b0deb105275568cdcef2823eb')),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_91fef5ed60605b854a2115d2410'))
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('asset', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assetId', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_d8cf9bdec7d2fad0852aec349c1'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_da96729a8b113377cfb6a62439c'))
    )
    op.create_table('kycs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('personalInformationVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('utilityBillImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utilityBillKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('utilityBillVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('identificationType', postgresql.ENUM('nin', 'passport', name='kycs_identificationtype_enum'), autoincrement=False, nullable=True),
    sa.Column('identificationNumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identificationImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identificationKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('identificationVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('bvn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bvnVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('faceLivenessImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('faceLivenessKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('faceLivenessVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sourceOfWealthImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sourceOfWealthKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sourceOfWealthVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('proofOfProfileImage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proofOfProfileKey', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('proofOfProfileVerified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updatedAt', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('FK_d294779a37e1c837b3ed0f5fe2f'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_6e61a5975007a8dae889765bbbf'))
    )
    op.drop_table('menu_items')
    op.drop_table('testimonials')
    op.drop_table('restaurant_info')
    op.drop_table('reservations')
    op.drop_table('newsletter_subscribers')
    op.drop_table('menu_categories')
    op.drop_table('awards')
    # ### end Alembic commands ###
