"""add gallery images table

Revision ID: 61521e19b253
Revises: cc65ef14387e
Create Date: 2025-07-25 03:35:10.355359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61521e19b253'
down_revision = 'cc65ef14387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Insert initial gallery images
    from sqlalchemy.sql import table, column
    import uuid, datetime
    gallery_images = table('gallery_images',
        column('id', sa.UUID()),
        column('url', sa.String()),
        column('alt', sa.String()),
        column('category', sa.String()),
        column('display_order', sa.Integer()),
        column('is_active', sa.Boolean()),
        column('created_at', sa.DateTime()),
    )
    images = [
        {"url": "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&h=600&fit=crop", "alt": "Elegant dining room with crystal chandeliers and warm ambiance", "category": "Interior Design"},
        {"url": "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800&h=600&fit=crop", "alt": "Signature truffle pasta with aged parmesan", "category": "Signature Dishes"},
        {"url": "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop", "alt": "Fine dining table setting with premium silverware", "category": "Table Settings"},
        {"url": "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&h=600&fit=crop", "alt": "Pan-seared salmon with seasonal vegetables", "category": "Signature Dishes"},
        {"url": "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800&h=600&fit=crop", "alt": "Chef Laurent preparing fresh handmade pasta", "category": "Kitchen Stories"},
        {"url": "https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&h=600&fit=crop", "alt": "Artisan tiramisu with gold leaf garnish", "category": "Dessert Artistry"},
        {"url": "https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&h=600&fit=crop", "alt": "Intimate dining area with fireplace", "category": "Interior Design"},
        {"url": "https://images.unsplash.com/photo-1424847651672-bf20a4b0982b?w=800&h=600&fit=crop", "alt": "Anniversary celebration with champagne service", "category": "Special Events"},
        {"url": "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=600&fit=crop", "alt": "Wagyu beef preparation with molecular techniques", "category": "Kitchen Stories"},
        {"url": "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800&h=600&fit=crop", "alt": "Chocolate soufflé with vanilla bean ice cream", "category": "Dessert Artistry"},
        {"url": "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=800&h=600&fit=crop", "alt": "Wine cellar with vintage collection", "category": "Wine Collection"},
        {"url": "https://images.unsplash.com/photo-1515669097368-22e68403d87b?w=800&h=600&fit=crop", "alt": "Private dining room for intimate gatherings", "category": "Private Events"},
    ]
    now = datetime.datetime.utcnow()
    for i, img in enumerate(images):
        op.execute(gallery_images.insert().values(
            id=str(uuid.uuid4()),
            url=img["url"],
            alt=img["alt"],
            category=img["category"],
            display_order=i,
            is_active=True,
            created_at=now
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_images')
    # ### end Alembic commands ###
